"""Load and validate report definition YAML into ReportDef dataclasses.

Report definitions are identified by UUID (not name) — the content-zip
import path requires a stable id so re-imports update in place.  UUIDs
are minted on first validate (same contract as views and dashboards).

YAML schema (see .claude/agents/report-author.md for the canonical spec):

    name: "[VCF Content Factory] My Report"
    description: "What this report shows"
    id: <auto-generated UUID on first validate>

    subject_types:
      - adapter_kind: VMWARE
        resource_kind: VirtualMachine
        type: self              # self | descendant
        # filter: optional metric filter JSON (advanced)

    sections:
      - type: CoverPage
      - type: TableOfContents
      - type: View
        view: "<exact view name>"     # resolved to UUID by loader
        orientation: Landscape        # Landscape | Portrait
        colorize: true                # colorize list view rows
      - type: Dashboard
        dashboard: "<exact dashboard name>"
        orientation: Landscape

    settings:
      show_page_footer: true
      output_formats:
        - pdf
        - csv

Cross-reference resolution:
  - View names are resolved by scanning views/ (or a configurable dir).
  - Dashboard names are resolved by scanning dashboards/.
  - Resolution happens at load time so validation catches broken refs.
"""
from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import yaml
import yaml.constructor
import yaml.resolver


def _strict_load(stream):
    """yaml.safe_load replacement that raises on duplicate mapping keys."""
    class _StrictKeyLoader(yaml.SafeLoader):
        pass

    def _no_duplicates(loader, node, deep=False):
        mapping = {}
        for key_node, value_node in node.value:
            key = loader.construct_object(key_node, deep=deep)
            if key in mapping:
                raise yaml.constructor.ConstructorError(
                    None, None,
                    f"duplicate key '{key}' found at {key_node.start_mark}",
                    key_node.start_mark,
                )
            mapping[key] = loader.construct_object(value_node, deep=deep)
        return mapping

    _StrictKeyLoader.add_constructor(
        yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
        _no_duplicates,
    )
    return yaml.load(stream, Loader=_StrictKeyLoader)



class ReportValidationError(ValueError):
    pass


_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)

# Supported section types.
SECTION_TYPES = {"CoverPage", "TableOfContents", "View", "Dashboard"}

# Fixed ContentKey values for the static section types.
_STATIC_CONTENT_KEYS = {
    "CoverPage": "COVER_PAGE",
    "TableOfContents": "TABLE_OF_CONTENTS",
}

VALID_ORIENTATIONS = {"Landscape", "Portrait"}
VALID_OUTPUT_FORMATS = {"pdf", "csv"}


@dataclass
class SubjectType:
    adapter_kind: str
    resource_kind: str
    type: str            # "self" or "descendant"
    filter: str = ""     # optional HTML-entity-encoded JSON filter


@dataclass
class Section:
    type: str            # CoverPage | TableOfContents | View | Dashboard
    # View sections
    view_name: str = ""   # author-written view name; resolved to UUID at render
    view_id: str = ""     # filled during load
    orientation: str = "Landscape"
    colorize: bool = True
    # Dashboard sections
    dashboard_name: str = ""
    dashboard_id: str = ""


@dataclass
class ReportSettings:
    show_page_footer: bool = True
    output_formats: List[str] = field(default_factory=lambda: ["pdf"])


@dataclass
class ReportDef:
    name: str
    description: str
    subject_types: List[SubjectType]
    sections: List[Section]
    settings: ReportSettings
    id: str = ""
    source_path: Optional[Path] = None
    released: bool = False   # publish gate
    version: str = "1.0.0"  # internal semver

    def validate(self, enforce_framework_prefix: bool = True) -> None:
        if not self.name.strip():
            raise ReportValidationError("name is required")
        if enforce_framework_prefix and not self.name.startswith("[VCF Content Factory] "):
            src = str(self.source_path) if self.source_path else self.name
            raise ReportValidationError(
                f'{src}: name "{self.name}" missing framework prefix '
                f'"[VCF Content Factory]". All factory-authored content must carry the literal '
                f'"[VCF Content Factory]" prefix (see CLAUDE.md §Hard rules #5). For third-party '
                f"bundle content, ensure the bundle manifest sets factory_native: false."
            )
        if not self.subject_types:
            raise ReportValidationError(
                f"{self.name}: at least one subject_type is required"
            )
        for st in self.subject_types:
            if not st.adapter_kind:
                raise ReportValidationError(
                    f"{self.name}: subject_type missing adapter_kind"
                )
            if not st.resource_kind:
                raise ReportValidationError(
                    f"{self.name}: subject_type missing resource_kind"
                )
            if st.type not in ("self", "descendant"):
                raise ReportValidationError(
                    f"{self.name}: subject_type.type must be 'self' or 'descendant'; "
                    f"got {st.type!r}"
                )
        if not self.sections:
            raise ReportValidationError(
                f"{self.name}: at least one section is required"
            )
        for sec in self.sections:
            if sec.type not in SECTION_TYPES:
                raise ReportValidationError(
                    f"{self.name}: section type must be one of "
                    f"{sorted(SECTION_TYPES)}; got {sec.type!r}"
                )
            if sec.type == "View":
                if not sec.view_name:
                    raise ReportValidationError(
                        f"{self.name}: View section missing 'view' name"
                    )
                if not sec.view_id:
                    raise ReportValidationError(
                        f"{self.name}: View section '{sec.view_name}' could not "
                        f"be resolved — ensure the view exists in views/"
                    )
                if sec.orientation not in VALID_ORIENTATIONS:
                    raise ReportValidationError(
                        f"{self.name}: View section orientation must be one of "
                        f"{sorted(VALID_ORIENTATIONS)}; got {sec.orientation!r}"
                    )
            if sec.type == "Dashboard":
                if not sec.dashboard_name:
                    raise ReportValidationError(
                        f"{self.name}: Dashboard section missing 'dashboard' name"
                    )
                if not sec.dashboard_id:
                    raise ReportValidationError(
                        f"{self.name}: Dashboard section '{sec.dashboard_name}' "
                        f"could not be resolved — ensure the dashboard exists in "
                        f"dashboards/"
                    )
                if sec.orientation not in VALID_ORIENTATIONS:
                    raise ReportValidationError(
                        f"{self.name}: Dashboard section orientation must be one of "
                        f"{sorted(VALID_ORIENTATIONS)}; got {sec.orientation!r}"
                    )
        for fmt in self.settings.output_formats:
            if fmt not in VALID_OUTPUT_FORMATS:
                raise ReportValidationError(
                    f"{self.name}: output_format must be one of "
                    f"{sorted(VALID_OUTPUT_FORMATS)}; got {fmt!r}"
                )


def _mint_id_into_file(path: Path) -> str:
    """Prepend ``id: <uuid4>`` to the YAML file, same contract as dashboards."""
    new_id = str(uuid.uuid4())
    original = path.read_text()
    path.write_text(f"id: {new_id}\n{original}")
    return new_id


def _build_view_index(views_dir: Path) -> dict[str, str]:
    """Return {view_name: view_id} by scanning views_dir for YAML files."""
    index: dict[str, str] = {}
    if not views_dir.exists():
        return index
    for p in sorted(views_dir.rglob("*.y*ml")):
        try:
            data = yaml.safe_load(p.read_text()) or {}
            vname = str(data.get("name", "")).strip()
            vid = str(data.get("id", "") or "").strip().lower()
            if vname and vid and _UUID_RE.match(vid):
                index[vname] = vid
        except Exception:
            pass  # non-fatal; will surface as unresolved view at validate
    return index


def _build_dashboard_index(dashboards_dir: Path) -> dict[str, str]:
    """Return {dashboard_name: dashboard_id} by scanning dashboards_dir."""
    index: dict[str, str] = {}
    if not dashboards_dir.exists():
        return index
    for p in sorted(dashboards_dir.rglob("*.y*ml")):
        try:
            data = yaml.safe_load(p.read_text()) or {}
            dname = str(data.get("name", "")).strip()
            did = str(data.get("id", "") or "").strip().lower()
            if dname and did and _UUID_RE.match(did):
                index[dname] = did
        except Exception:
            pass
    return index


def load_file(
    path: str | Path,
    views_dir: str | Path = "content/factory/views",
    dashboards_dir: str | Path = "content/factory/dashboards",
    enforce_framework_prefix: bool = True,
) -> "ReportDef":
    """Load and validate a single report definition YAML file.

    Mints a UUID into the file on first validate (same contract as views and
    dashboards).  Resolves view and dashboard name references to UUIDs by
    scanning the respective directories.

    Args:
        path:           Path to the report YAML file.
        views_dir:      Directory containing view definition YAMLs.
        dashboards_dir: Directory containing dashboard definition YAMLs.

    Returns:
        A validated ReportDef.

    Raises:
        ReportValidationError: if the YAML is invalid or a cross-reference
            cannot be resolved.
    """
    path = Path(path)
    views_dir = Path(views_dir)
    dashboards_dir = Path(dashboards_dir)

    try:
        data = _strict_load(path.read_text()) or {}
    except yaml.constructor.ConstructorError as exc:
        raise ReportValidationError(f"{path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ReportValidationError(f"{path}: expected a YAML mapping")

    # UUID minting — same pattern as dashboards/views loader
    report_id = str(data.get("id", "") or "").strip().lower()
    if not report_id:
        report_id = _mint_id_into_file(path)
    elif not _UUID_RE.match(report_id):
        raise ReportValidationError(
            f"{path}: id '{report_id}' is not a valid uuid4"
        )

    name = str(data.get("name", "")).strip()
    description = str(data.get("description", "") or "").strip()

    # subject_types
    subject_types: List[SubjectType] = []
    for raw_st in (data.get("subject_types") or []):
        subject_types.append(SubjectType(
            adapter_kind=str(raw_st.get("adapter_kind", "")).strip(),
            resource_kind=str(raw_st.get("resource_kind", "")).strip(),
            type=str(raw_st.get("type", "self")).strip().lower(),
            filter=str(raw_st.get("filter", "") or "").strip(),
        ))

    # Build view and dashboard indexes for cross-reference resolution
    view_index = _build_view_index(views_dir)
    dashboard_index = _build_dashboard_index(dashboards_dir)

    # sections
    sections: List[Section] = []
    for raw_sec in (data.get("sections") or []):
        sec_type = str(raw_sec.get("type", "")).strip()

        if sec_type in ("CoverPage", "TableOfContents"):
            sections.append(Section(type=sec_type))

        elif sec_type == "View":
            view_name = str(raw_sec.get("view", "") or "").strip()
            view_id = view_index.get(view_name, "")
            orientation = str(raw_sec.get("orientation", "Landscape") or "Landscape").strip()
            colorize_raw = raw_sec.get("colorize", True)
            colorize = bool(colorize_raw) if not isinstance(colorize_raw, bool) else colorize_raw
            sections.append(Section(
                type="View",
                view_name=view_name,
                view_id=view_id,
                orientation=orientation,
                colorize=colorize,
            ))

        elif sec_type == "Dashboard":
            dashboard_name = str(raw_sec.get("dashboard", "") or "").strip()
            dashboard_id = dashboard_index.get(dashboard_name, "")
            orientation = str(raw_sec.get("orientation", "Landscape") or "Landscape").strip()
            sections.append(Section(
                type="Dashboard",
                dashboard_name=dashboard_name,
                dashboard_id=dashboard_id,
                orientation=orientation,
            ))

        else:
            # Unknown section types are preserved so validate() can report them
            sections.append(Section(type=sec_type))

    # settings
    raw_settings = data.get("settings") or {}
    show_page_footer = bool(raw_settings.get("show_page_footer", True))
    raw_formats = raw_settings.get("output_formats") or ["pdf"]
    output_formats = [str(f).strip().lower() for f in raw_formats]
    settings = ReportSettings(
        show_page_footer=show_page_footer,
        output_formats=output_formats,
    )

    released_raw = data.get("released", False)
    released = bool(released_raw) if isinstance(released_raw, bool) else False
    version = str(data.get("version", "1.0.0") or "1.0.0").strip() or "1.0.0"

    rd = ReportDef(
        id=report_id,
        name=name,
        description=description,
        subject_types=subject_types,
        sections=sections,
        settings=settings,
        source_path=path,
        released=released,
        version=version,
    )
    rd.validate(enforce_framework_prefix=enforce_framework_prefix)
    return rd


def load_dir(
    directory: str | Path = "content/factory/reports",
    views_dir: str | Path = "content/factory/views",
    dashboards_dir: str | Path = "content/factory/dashboards",
    enforce_framework_prefix: bool = True,
) -> List[ReportDef]:
    """Load all report definition YAML files from a directory.

    Checks for duplicate names across the directory and raises
    ReportValidationError if any are found.
    """
    directory = Path(directory)
    if not directory.exists():
        return []
    out: List[ReportDef] = []
    seen: dict[str, Path] = {}
    for p in sorted(directory.rglob("*.y*ml")):
        rd = load_file(p, views_dir=views_dir, dashboards_dir=dashboards_dir, enforce_framework_prefix=enforce_framework_prefix)
        if rd.name in seen:
            raise ReportValidationError(
                f"duplicate report name '{rd.name}' "
                f"in {p} and {seen[rd.name]}"
            )
        seen[rd.name] = p
        out.append(rd)
    return out
