"""Parity coverage for the `--release` flag on sdk_buildkit's `build-sdk`.

BLOCKING follow-up (PR #32 review): the RULE-014 version guardrail added
`--release` to vcfops_managementpacks/cli.py's `build-sdk` subcommand (and
`_apply_release_flag`, which sets VCFCF_RELEASE_BUILD=1) but the buildkit
tarball's `python3 -m sdk_buildkit build-sdk` — a SEPARATE argparse CLI
generated by buildkit.py's _KIT_MAIN template — never got the same flag.
The CI release workflow (knowledge/designs/sdk-template-scaffold/build-pak-on-tag.yml)
invokes the buildkit CLI with `--release`, so every tag-triggered release
build was failing with `unrecognized arguments: --release` before a pak
was ever produced.

This test exercises the ASSEMBLED kit's __main__.py (via subprocess, exactly
as CI runs it — see test_buildkit_isolated_build.py for the isolation
pattern this borrows) and asserts:

  1. `--release` parses without an argparse error ("unrecognized arguments").
  2. Without `--release`, sdk_builder logs the dev-preview (0.0.0.<build>)
     stamp line.
  3. With `--release`, sdk_builder logs the release (adapter.yaml version)
     stamp line — proving VCFCF_RELEASE_BUILD=1 actually reached
     sdk_builder._is_release_build() through the kit's own env-var
     injection (buildkit.py's _apply_release_flag), not just that the flag
     parsed.

Both builds are expected to fail downstream at the Java/SDK-jar step (no
vrops-adapters-sdk-2.2.jar in CI/test envs) — sdk_builder logs the version
stamp (sdk_builder.py:_stamp_build_version) *before* it reaches
_ensure_framework_jar(), so the marker line is reliably present on stderr
regardless of that later failure.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

import pytest


def _get_buildkit_internals():
    from vcfops_managementpacks.buildkit import (
        _FACTORY_SOURCES,
        _IMPORT_REWRITES,
        _apply_rewrites,
        _KIT_INIT,
        _KIT_MAIN,
    )
    return _FACTORY_SOURCES, _IMPORT_REWRITES, _apply_rewrites, _KIT_INIT, _KIT_MAIN


def _assemble_kit_python_only(kit_dir: Path) -> None:
    """Copy and rewrite all kit Python modules into kit_dir/sdk_buildkit/.

    Mirrors test_buildkit_isolated_build.py's helper of the same name —
    Python-module layer only, no tarball/reference-pak needed to exercise
    argparse + the version-stamp log line.
    """
    _FACTORY_SOURCES, _IMPORT_REWRITES, _apply_rewrites, _KIT_INIT, _KIT_MAIN = (
        _get_buildkit_internals()
    )

    pkg_dir = kit_dir / "sdk_buildkit"
    pkg_dir.mkdir(parents=True)

    (pkg_dir / "__init__.py").write_text(_KIT_INIT, encoding="utf-8")
    (pkg_dir / "__main__.py").write_text(_KIT_MAIN, encoding="utf-8")

    for dest_name, src_path in _FACTORY_SOURCES.items():
        if not src_path.is_file():
            continue
        source_text = src_path.read_text(encoding="utf-8")
        rules = _IMPORT_REWRITES.get(dest_name, [])
        if rules:
            patched_text = _apply_rewrites(source_text, rules)
            (pkg_dir / dest_name).write_text(patched_text, encoding="utf-8")
        else:
            (pkg_dir / dest_name).write_bytes(src_path.read_bytes())

    (pkg_dir / "adapter_runtime").mkdir(exist_ok=True)

    fw_src_real = (
        Path(__file__).parent.parent.parent
        / "src" / "vcfops_managementpacks" / "adapter_framework" / "src"
    )
    fw_dst = pkg_dir / "adapter_framework" / "src"
    if fw_src_real.is_dir():
        import shutil
        shutil.copytree(str(fw_src_real), str(fw_dst))
    else:
        fw_dst.mkdir(parents=True, exist_ok=True)


def _make_isolated_env(kit_parent: Path) -> dict:
    """Sanitised subprocess env: only the kit parent dir on PYTHONPATH."""
    repo_root = str(Path(__file__).parent.parent.parent.resolve())
    env = os.environ.copy()
    existing_pp = env.get("PYTHONPATH", "")
    cleaned_entries = [
        e for e in existing_pp.split(os.pathsep) if e
        if not Path(e).resolve() == Path(repo_root)
    ]
    cleaned_entries.insert(0, str(kit_parent))
    env["PYTHONPATH"] = os.pathsep.join(cleaned_entries)
    # Make sure a stray VCFCF_RELEASE_BUILD from the host env doesn't leak
    # into the "default build" subprocess call.
    env.pop("VCFCF_RELEASE_BUILD", None)
    return env


_ADAPTER_YAML = textwrap.dedent("""\
    name: "VCF Content Factory Release Flag Test Adapter"
    version: "1.2.3"
    build_number: 42
    adapter_kind: "release_flag_test"
    tier: 2
    description: "Synthetic adapter for buildkit --release flag parity test."
    entry_class: "com.vcfcf.adapters.releaseflag.ReleaseFlagAdapter"
    released: false
""")

_DESCRIBE_XML = textwrap.dedent("""\
    <?xml version="1.0" encoding="UTF-8"?>
    <AdapterKind key="release_flag_test" nameKey="1" version="1">
      <ResourceKinds>
        <ResourceKind key="release_flag_test_world" nameKey="2" type="1"/>
      </ResourceKinds>
    </AdapterKind>
""")

_JAVA_SRC = textwrap.dedent("""\
    package com.vcfcf.adapters.releaseflag;
    public class ReleaseFlagAdapter {}
""")


def _write_fixture_adapter(base: Path) -> Path:
    project_dir = base / "release_flag_adapter"
    project_dir.mkdir(parents=True)

    (project_dir / "adapter.yaml").write_text(_ADAPTER_YAML, encoding="utf-8")
    (project_dir / "describe.xml").write_text(_DESCRIBE_XML, encoding="utf-8")

    src_dir = (
        project_dir / "src" / "main" / "java" / "com" / "vcfcf" / "adapters" / "releaseflag"
    )
    src_dir.mkdir(parents=True)
    (src_dir / "ReleaseFlagAdapter.java").write_text(_JAVA_SRC, encoding="utf-8")

    return project_dir


def _run_kit_build_sdk(project_dir: Path, output_dir: Path,
                        extra_args: list[str], env: dict) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "sdk_buildkit", "build-sdk",
         str(project_dir), "--output", str(output_dir), *extra_args],
        capture_output=True,
        text=True,
        cwd=tempfile.gettempdir(),
        env=env,
        timeout=55,
    )


@pytest.fixture
def _kit_and_fixture(tmp_path):
    kit_root = tmp_path / "kit"
    fixture_root = tmp_path / "fixture"
    fixture_root.mkdir()

    _assemble_kit_python_only(kit_root)
    project_dir = _write_fixture_adapter(fixture_root)
    output_dir = tmp_path / "output"
    output_dir.mkdir()

    env = _make_isolated_env(kit_root)
    return project_dir, output_dir, env


@pytest.mark.timeout(60)
def test_buildkit_release_flag_parses_without_argparse_error(_kit_and_fixture):
    """`--release` must be a recognized argument on the kit's build-sdk parser."""
    project_dir, output_dir, env = _kit_and_fixture

    result = _run_kit_build_sdk(project_dir=project_dir, output_dir=output_dir,
                                 extra_args=["--release"], env=env)

    combined = result.stdout + result.stderr
    assert "unrecognized arguments" not in combined, (
        "sdk_buildkit build-sdk --release raised an argparse error — the "
        "kit's __main__.py parser does not know about --release.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


@pytest.mark.timeout(60)
def test_buildkit_default_build_stamps_dev_preview(_kit_and_fixture):
    """Default (no --release) build-sdk through the kit stamps 0.0.0.<build>."""
    project_dir, output_dir, env = _kit_and_fixture

    result = _run_kit_build_sdk(project_dir=project_dir, output_dir=output_dir,
                                 extra_args=[], env=env)

    combined = result.stdout + result.stderr
    assert "unrecognized arguments" not in combined
    assert "version stamp -> dev preview -> 0.0.0.42" in combined, (
        "Expected the dev-preview version-stamp INFO line on stderr.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    assert "version stamp -> release build" not in combined


@pytest.mark.timeout(60)
def test_buildkit_release_flag_stamps_declared_version(_kit_and_fixture):
    """`--release` through the kit must reach sdk_builder as VCFCF_RELEASE_BUILD=1,
    producing the release (adapter.yaml 1.2.3) version-stamp line — not just
    parsing cleanly.
    """
    project_dir, output_dir, env = _kit_and_fixture

    result = _run_kit_build_sdk(project_dir=project_dir, output_dir=output_dir,
                                 extra_args=["--release"], env=env)

    combined = result.stdout + result.stderr
    assert "unrecognized arguments" not in combined
    assert "version stamp -> release build -> 1.2.3.42" in combined, (
        "Expected the release version-stamp INFO line (adapter.yaml 1.2.3) "
        "on stderr — VCFCF_RELEASE_BUILD did not reach sdk_builder through "
        "the kit's --release flag.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    assert "version stamp -> dev preview" not in combined
